Fixed inconsistent spelling
davewiebe/GameBot pull request #7
Opened 2020-11-20 02:58 UTC by agoryelov

2020-11-20 05:07 UTC, agoryelov reviewed
LGTM

2020-11-20 05:35 UTC, jonvandermey requested changes

2020-11-20 05:35 UTC, jonvandermey commented on PerudoBot/Modules/LiarCommands.cs
> +                if (PlayerEligeebleForSafeguard(game.Penalty == 0, playerWhoShouldGoNext.NumberOfDice, penalty)) {
How dare you

2020-11-20 17:05 UTC, guardianz95 commented on PerudoBot/Modules/LiarCommands.cs
> +                if (PlayerEligeebleForSafeguard(game.Penalty == 0, playerWhoShouldGoNext.NumberOfDice, penalty)) {
What is the world is this abomination

2020-11-24 19:31 UTC, jonvandermey commented
Was fixed in PR #8

2020-11-24 19:31 UTC, closed without merging